%%{init: {'theme': 'base', 'flowchart': {'useMaxWidth': false}}}%%
flowchart TB
  Cliente[Cliente en Internet]
  APIGW[API Gateway regional]
  subgraph vpc [VPC 10.0.0.0/16]
    subgraph public [Subnets publicas /24]
      NAT[NAT Gateway AZ1]
      NLB[NLB interno]
    end
    subgraph private [Subnets privadas /24]
      Nodos[Nodos EKS y Karpenter]
      Pods[Pods FastAPI]
    end
  end
  DDB[(DynamoDB)]

  Cliente --> APIGW
  APIGW -->|VPC Link| NLB
  NLB --> Pods
  Nodos --> Pods
  private --> NAT
  Pods --> DDB
