%%{init: {'theme': 'base', 'flowchart': {'useMaxWidth': false}}}%%
flowchart TB
  Cliente[Cliente] --> APIGW[API Gateway regional]
  APIGW -->|VPC Link| NLB
  subgraph vpc [VPC 10.0.0.0/16]
    direction LR
    subgraph public [Subnets publicas]
      NAT[NAT Gateway]
      NLB[NLB interno]
    end
    subgraph private [Subnets privadas]
      Nodos[Nodos EKS]
      Pods[Pods FastAPI]
    end
  end
  Nodos --> Pods
  Pods --> NAT
  Pods --> DDB[(DynamoDB)]
