%%{init: {'flowchart': {'useMaxWidth': false}}}%%
flowchart TB
  subgraph peticion [Camino de la peticion]
    direction LR
    Cliente[Cliente HTTP] --> APIGW[API Gateway]
    APIGW --> VpcLink[VPC Link]
    VpcLink --> NLB[NLB interno]
    NLB --> Istio[Istio]
    Istio --> FastAPI[FastAPI]
  end
  subgraph apoyo [Datos y capacidad]
    direction LR
    FastAPI2[FastAPI] --> IRSA[Rol IRSA]
    IRSA --> DDB[(DynamoDB)]
    EKS[EKS] --> Karpenter[Karpenter Spot]
    Karpenter --> FastAPI2
  end
  peticion --> apoyo
