%%{init: {'theme': 'base', 'flowchart': {'useMaxWidth': false}}}%%
flowchart TB
  C[Cliente] -->|HTTPS| A[API Gateway]
  A -->|HTTP proxy| V[VPC Link]
  V --> N[NLB puerto 80]
  N --> I[Istio puerto 8080]
  I --> S[VirtualService]
  S --> P[FastAPI puerto 8000]
  P -->|IRSA| T[(DynamoDB)]
