%%{init: {'flowchart': {'useMaxWidth': false}}}%%
flowchart TB
  NLB[NLB puerto 80] --> IG[Ingress puerto 8080]
  IG --> GW[Gateway]
  GW --> VS[VirtualService]
  VS -->|/productos| SVC[Service :8000]
  VS -->|/clientes| SVC
  SVC --> Pod[Pod FastAPI]
