%%{init: {'theme': 'base', 'flowchart': {'useMaxWidth': false}}}%%
flowchart TB
  Pod[Pod Pending] --> Sched[Scheduler]
  Sched --> Ctrl[Karpenter IRSA]
  Ctrl --> Pool[NodePool Spot]
  Pool --> Class[EC2NodeClass AL2023]
  Class --> Ec2[Instancia Spot]
  Ec2 --> Join[Nodo Ready]
  Join --> Pod
