%%{init: {'flowchart': {'useMaxWidth': false}}}%%
flowchart LR
  subgraph ns [Namespace api-mercado]
    direction TB
    SA[ServiceAccount IRSA] --> DEP[Deployment]
    CM[ConfigMap del codigo] --> DEP
    DEP --> SVC[Service :8000]
    VS[VirtualService] --> SVC
  end
  DEP --> DDB[(DynamoDB)]
