%%{init: {'flowchart': {'useMaxWidth': false}}}%%
flowchart TB
  Infra[make infra] --> Kube[make kubeconfig]
  Kube --> Plat[make platform]
  Plat --> App[make app]
  App --> Nlb[make discover-nlb]
  Nlb --> Api[make api]
  Api --> Smoke[make smoke]
